pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Checkout') {
            steps {
                // Clone the repository
                git branch: 'main', url: 'https://github.com/tripc07/simple-node-js-react-npm-app.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Generate OpenAPI Documentation') {
            steps {
                script {
                    // If specific commands are needed to generate OpenAPI docs, add them here.
                    // Example: sh 'npm run generate-docs'
                    sh 'echo "Generate OpenAPI Documentation"'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
        stage('Publish OpenAPI Documentation') {
            steps {
                script {
                    // Example: Copy the OpenAPI documentation to an artifact directory
                    sh 'mkdir -p docs'
                    sh 'cp -r public/api-docs docs/'
                    archiveArtifacts artifacts: 'docs/**'
                }
            }
        }
    }
    post {
        always {
            // Clean workspace after build
            cleanWs()
        }
    }
}
